#---------------------------------------------------------------------------
#
# MTVehicles Created by GamerJoep_, download on https://mtvehicles.nl
# Join the discord for support, you can find it on the site ^
#
#---------------------------------------------------------------------------

# Do not touch this! If you change it it will brake.
Config-Versie: 2.0.9

# Do not change this, else your plugin can be broke.
messagesLanguage: ns

# /vehicle menu default size, max size is 6.
vehicleMenuSize: 3

# If set to true, helicopter blades will always stay on top of the helicopter. If set to false they will only appear when you get in the vehicle and remove when you get out.
wiekens-always-on: true

# If set to true you can't pick up the vehicle after ridden on water, else you will need the permission mtvehicles.anwb
anwb: true

# If set to false you will not be able to open the trunk.
kofferbakEnabled: true

# Do you want to turn off gasoline for ALL cars?
benzine: true

# Jerrycan size for in the /vehicle benzine menu.
jerrycans:
  - 25
  - 50
  - 75

# Leave it on true if you want to be up-to-date!
# Turn it off and you will not get any messages for updates.
# auto-update will show on server join if you have the permission mtvehicles.update
# If set on false the /vehicle update command will not work either.
auto-update: true

# Give players the ability put themselves owner
spelerSetOwner: false

# Maximum flying height for helicopters
helicopterMaxHight: 150

# Turn on if you do not want players to pickup vehicles.
carPickup: false